//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocios
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int usuario_id { get; set; }
        public string usuario_apellido { get; set; }
        public string usuario_nombre { get; set; }
        public string usuario_email { get; set; }
        public string usuario_telefono { get; set; }
        public Nullable<System.DateTime> usuario_fecha_nacimiento { get; set; }
        public string usuario_userAspNet { get; set; }
        public string usuario_direccion { get; set; }
    }
}
